### ISSUE TITLE
Great Work! Suggestions for Including Related Work in Your Paper

### ISSUE THREAD

**Issue by bbsngg** [ys-zong/MIRB#1]
Hi Yongshuo,

Thank you for your significant contribution with this impressive work.

We would like to kindly draw your attention to our previous work, [MileBench](https://arxiv.org/abs/2404.18532), which also includes multi-image data for benchmarking multimodal LLMs. Our work also includes various categories of multi-image reasoning tasks, although it is not as diverse as MIRB, such as in areas like code understanding. Given the comprehensive nature of your work, we believe that referencing MileBench would be a valuable addition to your related work section.

Thank you for your consideration.

**Comment by ys-zong** [comment]
Thanks for your interest and suggestion Dingjie! We will cite your paper in our next version:)

**Comment by bbsngg** [comment]
Thank you for your positive response. We are excited to see more of your fascinating contributions in the future.
