### ISSUE TITLE
Question about eval file

### ISSUE THREAD

**Issue by Bohao-Lee** [ys-zong/MIRB#2]
Thank you for your great work! I have encountered some questions when I try to evaluate model. There are many json in huggingface but in the code you provide, it seems that only evaluation analogy.json and codeu.json. Also, I want to obtain my model performance in 
'''Knowledge | Reasoning | Perception | Multi-Hop | Average''', but I don't know which json I need to evaluate and how to obtain these performance. Can you provide corresponding illustration?

**Comment by ys-zong** [comment]
Hi, thanks for your interest. 
You can just append more subsets (and models) as arguments for inference and evaluation as long as they match the names of json files in HF (check [here](https://github.com/ys-zong/MIRB/blob/ee2e96e5cb1f8bcc8cdf8505e31906f99aaee8ec/inference.py#L18)).
For example,
```bash
python inference.py --engine phi3-vision idefics2-8b --dataset codeu analogy arxiv attribute visual_chain plot_code codeu sightseeing food image_jigsaw 3d_scene
python evaluate.py --engine phi3-vision idefics2-8b --dataset codeu analogy arxiv attribute visual_chain plot_code codeu sightseeing food image_jigsaw 3d_scene
```
And I just uploaded a script to print the final results. After you get the results from the above steps, just run:
```
python results_summary.py
```
Then you will see the results as different groups.

**Comment by Bohao-Lee** [comment]
Thank you for your quick response. I have read these codes, so if I want to obtain these results, do I need to inference and evaluate all 11 JSON files in the results_summary.py to obtain the final performance?

**Comment by ys-zong** [comment]
After you run `python evaluate.py  --your_args` for all subsets, there will be a ['results.json'](https://github.com/ys-zong/MIRB/blob/ee2e96e5cb1f8bcc8cdf8505e31906f99aaee8ec/evaluate.py#L38) saved in the current directory. You just need to run results_summary.py once to get the final performance.

**Comment by Bohao-Lee** [comment]
Thanks a lot!
