### ISSUE TITLE
你好，请问该如何去计算这个benchmark的平均分

### ISSUE THREAD

**Issue by czczup** [ys-zong/MIRB#3]

**Comment by ys-zong** [comment]
Hi, you can check if #2 can address you question - specially [here](https://github.com/ys-zong/MIRB/issues/2#issuecomment-2228516971)

**Comment by czczup** [comment]
Thanks~

**Comment by czczup** [comment]
感觉minicpm v2.6报的点复现不出来，很迷。我测出来InternVL2-8B大概在50左右...

<img width="867" alt="image" src="https://github.com/user-attachments/assets/654634c2-30a3-414b-9fbe-12ffd0488e21">

**Comment by ys-zong** [comment]
我在[lmms-eval](https://github.com/EvolvingLMMs-Lab/lmms-eval)有个[PR](https://github.com/EvolvingLMMs-Lab/lmms-eval/pull/150)。可能他们用的是那里的实现？answer matching的时候会有点implementation的区别。
